EClaim.Application/EClaim.Application/Controllers/ClaimController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.EMMA;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Wordprocessing;
using EClaim.Application.Enum;
using EClaim.Application.Models;
using EClaim.Application.Models.Response;
using EClaim.Application.Models.ViewModel;
using EClaim.Application.Notification;
using EClaim.Application.Notification.EMAILService;
using EClaim.Application.Notification.SMSService;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Newtonsoft.Json;
using System.Reflection;
using System.Security.Claims;
using System.Text;

namespace EClaim.Application.Controllers
{
    [Authorize]
    public class ClaimController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IWebHostEnvironment _env;
        private readonly HttpClient _httpClient;
        private readonly INotificationFactory _notificationFactory;
        private readonly IConfiguration _config;
        private readonly string _uploadFilePath = "uploads";
        private readonly IViewRenderService _viewRenderService;
        private readonly IEmailBuilder _emailBuilder;
        private readonly ISmsBuilder _smsBuilder;

        public ClaimController(IHttpClientFactory httpClientFactory, IWebHostEnvironment env, INotificationFactory notificationFactory, IConfiguration config, IViewRenderService viewRenderService, IEmailBuilder builder, ISmsBuilder smsBuilder)
        {
            _httpClientFactory = httpClientFactory;
            _env = env;
            _httpClient = _httpClientFactory.CreateClient("api");
            _notificationFactory = notificationFactory;
            _config = config;
            _viewRenderService = viewRenderService;
            _emailBuilder = builder;
            _smsBuilder = smsBuilder;
        }

        [HttpGet]
        [Authorize(Roles = "Claimant")]
        public async Task<IActionResult> Index()
        {
            ClaimSubmissionViewModel claimSubmissionViewModel = new ClaimSubmissionViewModel();
            return View(claimSubmissionViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Claimant")]
        public IActionResult Submit() => View();

        [HttpPost]
        [Authorize(Roles = "Claimant")]
        public async Task<IActionResult> Submit(ClaimSubmissionViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var userId = int.Parse(User.FindFirst("userId").Value);

            var claim = new ClaimSubmissionModel
            {
                ClaimType = model.ClaimType,
                Description = model.Description,
                UserId = userId
            };

            var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif" };
            if (model.Documents != null)
            {
                foreach (var file in model.Documents)
                {
                    var extension = Path.GetExtension(file.FileName).ToLowerInvariant();
                    if (!allowedExtensions.Contains(extension))
                    {
                        ModelState.AddModelError("Documents", "Only image files (.jpg, .jpeg, .png, .gif) are allowed.");
                        return View(); 
                    }

                    var path = Path.Combine(_env.WebRootPath, _uploadFilePath, file.FileName);
                    using var stream = System.IO.File.Create(path);
                    await file.CopyToAsync(stream);

                    claim.Documents.Add(new ClaimDocumentModel
                    {
                        FileName = file.FileName,
                        FilePath = $"/{_uploadFilePath}/{file.FileName}"
                    });
                }

            }

            var content = new StringContent(JsonConvert.SerializeObject(claim), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("api/Claim", content);

            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError("", "Claim submition failed.");
                return View(model);
            }

            string responseBody = await response.Content.ReadAsStringAsync();
            ClaimSubmissionModel result = JsonConvert.DeserializeObject<ClaimSubmissionModel>(responseBody);
            await SendNotification(result.Id);
            return RedirectToAction($"Details", new { id = result.Id });
        }



        [HttpGet]
        //[Authorize(Roles = "Claimant")]
        public async Task<IActionResult> Details(int id)
        {
            var response = await _httpClient.GetStringAsync($"api/Claim?id={id}");
            var claimRequestResponse = JsonConvert.DeserializeObject<ClaimRequestResponse>(response);
            

            return View(claimRequestResponse);
        }

        private async Task SendNotification(int claimId)
        {
            var IsNotificationEnable = bool.Parse(_config["IsNotificationEnable"]);
            if (IsNotificationEnable)
            {
                var response = await _httpClient.GetStringAsync($"api/Claim?id={claimId}");
                var claimRequestResponse = JsonConvert.DeserializeObject<ClaimRequestResponse>(response);

                var type = Convert.ToString(_config["NotificationType"]);
                NotificationType notificationType = type.ToUpper() switch
                {
                    "EMAIL" => NotificationType.EMAIL,
                    "SMS" => NotificationType.SMS,
                    _ => throw new ArgumentException("Invalid notification type")
                };

                var service = _notificationFactory.GetNotificationService(notificationType);
                if (notificationType == NotificationType.EMAIL)
                {
                    var IsEnable = bool.Parse(_config["Smtp:IsEnable"]); 
                    var emailSubject = "Claim Request Confirm Mail";
                    string htmlContent = await _viewRenderService.RenderToStringAsync("Views/Claim/Details.cshtml", claimRequestResponse);

                    EmailMessage email = _emailBuilder
                                            .SetRecipient(IsEnable ? claimRequestResponse.User.Email : _config["Smtp:From"])
                                            .SetSubject(emailSubject)
                                            .SetBody(htmlContent, true)
                                            .Build();

                    await service.SendNotificationlAsync(email);
                }
                else
                {

                    var userEmail = User.FindFirst("emailaddress").Value;
                    

                    var IsEnable = bool.Parse(_config["Smtp:IsEnable"]);
                    //await service.SendNotificationlAsync(
                    //   IsEnable ? userEmail : _config["Smtp:From"],
                    // emailSubject, htmlContent);

                    SMSMessage sms = _smsBuilder
                                            .SetRecipient(IsEnable ? claimRequestResponse.User.Phone : _config["SMSConfig:FromPhone"])
                                            .SetSubject("")
                                            .SetBody("Your claim submited/status updated", true)
                                            .Build();
                    await service.SendNotificationlAsync(sms);
                }
            }
        }

        [HttpGet]
        //[Authorize(Roles = "Adjuster,Approver,Admin")]
        public async Task<IActionResult> ClaimDetails(DateTime fromDate, DateTime toDate)
        {
            var userId = int.Parse(User.FindFirst("userId").Value);
            var response = await _httpClient.GetStringAsync($"api/Claim/GetClaimDetails/{fromDate.ToString("dd-MMM-yyyy")}/{toDate.ToString("dd-MMM-yyyy")}/{userId}");

            var claimRequestResponse = JsonConvert.DeserializeObject<List<ClaimRequestResponse>>(response);
            return View(claimRequestResponse);
        }

        [HttpPost]
        public async Task<IActionResult> TakeAction(ClaimStatusUpdateViewModel model)
        {
            model.UserId = int.Parse(User.FindFirst("userId").Value);

            var content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
            var response = await _httpClient.PatchAsync($"api/Claim/UpdateStatus", content);

            if (response.IsSuccessStatusCode)
            {
                await SendNotification(model.Id);
                return RedirectToAction("Search");
            }
            else
            {
                var error = await response.Content.ReadAsStringAsync();
                throw new Exception($"Failed to update status: {response.StatusCode} - {error}");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Search(ClaimSearchViewModel model)
        {
            if (model.FromDate != null && model.ToDate != null && model.FromDate > model.ToDate)
            {
                ModelState.AddModelError("", "FromDate cannot be greater than ToDate");
                return View(model);
            }
            List<ClaimRequestResponse>? claimRequestResponse = await SearchClaims(model);
            model.Results = claimRequestResponse;
            return View(model);
        }

        private async Task<List<ClaimRequestResponse>?> SearchClaims(ClaimSearchViewModel model)
        {
            var userId = int.Parse(User.FindFirst("userId").Value);
            model.UserId = userId;

            var queryParams = new Dictionary<string, string?>
                {
                    { "UserId", model.UserId.ToString() },
                    { "Status", model.Status },

EClaim.Application/EClaim.Application/Controllers/UsersController.cs
using EClaim.Application.Models;
using EClaim.Application.Models.ViewModel;
using EClaim.Application.Notification;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace EClaim.Application.Controllers
{
    public class UsersController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly INotificationService _emailService;
        private readonly IConfiguration _config;
        private readonly HttpClient _httpClient;

        public UsersController(IHttpClientFactory httpClientFactory, INotificationService emailService, IConfiguration config)
        {
            _httpClientFactory = httpClientFactory;
            _emailService = emailService;
            _config = config;
            _httpClient = _httpClientFactory.CreateClient("api");
        }

        // GET: UsersController
        public async Task<IActionResult> Index(UsersSearchViewModel model)
        {
            if (model.FromDate != null && model.ToDate != null && model.FromDate > model.ToDate)
            {
                ModelState.AddModelError("", "FromDate cannot be greater than ToDate");
                return View(model);
            }

            var userId = int.Parse(User.FindFirst("userId").Value);
            model.UserId = userId;

            bool? IsEmailVerified = null;
            if (!string.IsNullOrEmpty(model.IsEmailVerified))
            {
                IsEmailVerified = model.IsEmailVerified.Equals("Yes") ? true : false;
            }

            var queryParams = new Dictionary<string, string?>
                {
                    { "UserId", model.UserId.ToString() },
                    { "FullName", model.FullName },
                    { "Email", model.Email },
                    { "Phone", model.Phone },
                    { "Role", model.Role },
                    { "IsEmailVerified", IsEmailVerified.ToString() },
                    { "FromDate", model.FromDate?.ToString("yyyy-MMM-dd") },
                    { "ToDate", model.ToDate?.ToString("yyyy-MMM-dd") },
                };

            var query = string.Join("&", queryParams
                .Where(kvp => !string.IsNullOrEmpty(kvp.Value))
                .Select(kvp => $"{kvp.Key}={Uri.EscapeDataString(kvp.Value)}"));


            var response = await _httpClient.GetStringAsync($"api/Users/GetUsers?{query}");
            var usersViewModel = JsonConvert.DeserializeObject<List<UsersViewModel>>(response);

            model.Results = usersViewModel;
            return View(model);
        }

        // GET: UsersController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetStringAsync($"api/Users/{id}");
            var usersViewModel = JsonConvert.DeserializeObject<UsersViewModel>(response);
            return View(usersViewModel);
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UsersViewModel model)
        {
            var userId = int.Parse(User.FindFirst("userId").Value);
            var user = new UserCreateModel
            {
                Id = id,
                FullName = model.FullName,
                Phone = model.Phone,
                Email = model.Email,
                Address = model.Address,
                Role = model.Role,
                IsEmailVerified = model.IsEmailVerified,
                UserId = userId
            };

            var content = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync("api/Users", content);

            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError("", "Registration failed.");
                return View(model);
            }

            string responseBody = await response.Content.ReadAsStringAsync();
            ClaimSubmissionModel result = JsonConvert.DeserializeObject<ClaimSubmissionModel>(responseBody);
            return RedirectToAction(nameof(Index));

        }

        // GET: UsersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UsersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

EClaim.Application/EClaim.Application/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@{
    var user = HttpContextAccessor.HttpContext.User;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EClaim.Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EClaim.Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EClaim.Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && user.IsInRole("Claimant"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Claim" asp-action="Submit">Submit Claim</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && user.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Profile management</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Claim" asp-action="Search" >Claim Search</a>
                        </li>
                    </ul>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ms-auto">

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <span class="nav-link">Hello, @User.Identity.Name!</span>
                                </li>
                                <li class="nav-item">
                                    <form asp-controller="Account" asp-action="Logout" method="post" class="d-inline">
                                        @Html.AntiForgeryToken()
                                        <button type="submit" class="btn btn-link nav-link">Logout</button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EClaim.Application - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>